export const INDIAN_LANGUAGES = [
  { code: 'hi', name: 'Hindi' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'mr', name: 'Marathi' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'bn', name: 'Bengali' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'en', name: 'English' },
];

export const INDIAN_VOICES = {
  elevenlabs: [
    { id: 'oH8YmZXJYEZq5ScgoGn9', name: 'Aakash – Friendly Support' },
    { id: 'X4ExprIXDKrWcHdtGysh', name: 'Anjura – Confident' },
    { id: 'SXuKWBhKoIoAHKlf6Gt3', name: 'Gaurav – Professional' },
    { id: 'N09NFwYJJG9VSSgdLQbT', name: 'Ishan – Bold & Upbeat' },
    { id: 'U9wNM2BNANqtBCawWLgA', name: 'Himanshu – Calm' },
    { id: 'h061KGyOtpLYDxcoi8E3', name: 'Ravi – Gentle' },
    { id: 'Ock0AL5DBkvTUDePt4Hm', name: 'Viraj – Commanding' },
    { id: 'nwj0s2LU9bDWRKND5yzA', name: 'Bunty – Fun' },
    { id: 'amiAXapsDOAiHJqbsAZj', name: 'Priya – Confident \u2640' },
    { id: '6JsmTroalVewG1gA6Jmw', name: 'Sia – Friendly \u2640' },
    { id: '9vP6R7VVxNwGIGLnpl17', name: 'Suhana – Joyful \u2640' },
    { id: 'hO2yZ8lxM3axUxL8OeKX', name: 'Mini – Cute \u2640' },
    { id: 's0oIsoSJ9raiUm7DJNzW', name: '\u2B50 Default Voice' },
  ],
  smallest: [
    { id: 'raj', name: 'Raj – Confident \u2642' },
    { id: 'arnav', name: 'Arnav – Friendly \u2642' },
    { id: 'raman', name: 'Raman – Natural \u2642' },
    { id: 'raghav', name: 'Raghav – Professional \u2642' },
    { id: 'aarav', name: 'Aarav – Calm \u2642' },
    { id: 'ankur', name: 'Ankur – Relaxed \u2642' },
    { id: 'aravind', name: 'Aravind – Narrative \u2642' },
    { id: 'saurabh', name: 'Saurabh – Bold \u2642' },
    { id: 'chetan', name: 'Chetan – Strong \u2642' },
    { id: 'ashish', name: 'Ashish – Warm \u2642' },
    { id: 'kajal', name: 'Kajal – Friendly \u2640' },
    { id: 'pragya', name: 'Pragya – Upbeat \u2640' },
    { id: 'nisha', name: 'Nisha – Kind \u2640' },
    { id: 'deepika', name: 'Deepika – Bold \u2640' },
    { id: 'diya', name: 'Diya – Young \u2640' },
    { id: 'sushma', name: 'Sushma – Strong \u2640' },
    { id: 'shweta', name: 'Shweta – Conversational \u2640' },
    { id: 'ananya', name: 'Ananya – Narrative \u2640' },
    { id: 'mithali', name: 'Mithali – Classic \u2640' },
    { id: 'saina', name: 'Saina – Bold \u2640' },
    { id: 'sanya', name: 'Sanya – Friendly \u2640' },
    { id: 'pooja', name: 'Pooja – Informative \u2640' },
    { id: 'mansi', name: 'Mansi – Narrative \u2640' },
  ],
  sarvam: [
    { id: 'aditya', name: 'Aditya – Default \u2642' },
    { id: 'rahul', name: 'Rahul – Conversational \u2642' },
    { id: 'amit', name: 'Amit – Professional \u2642' },
    { id: 'dev', name: 'Dev – Young \u2642' },
    { id: 'rohan', name: 'Rohan – Friendly \u2642' },
    { id: 'varun', name: 'Varun – Calm \u2642' },
    { id: 'kabir', name: 'Kabir – Bold \u2642' },
    { id: 'manan', name: 'Manan – Warm \u2642' },
    { id: 'sumit', name: 'Sumit – Natural \u2642' },
    { id: 'ratan', name: 'Ratan – Mature \u2642' },
    { id: 'aayan', name: 'Aayan – Young \u2642' },
    { id: 'shubh', name: 'Shubh – Energetic \u2642' },
    { id: 'ashutosh', name: 'Ashutosh – Deep \u2642' },
    { id: 'advait', name: 'Advait – Smooth \u2642' },
    { id: 'ritu', name: 'Ritu – Warm \u2640' },
    { id: 'priya', name: 'Priya – Friendly \u2640' },
    { id: 'neha', name: 'Neha – Professional \u2640' },
    { id: 'pooja', name: 'Pooja – Kind \u2640' },
    { id: 'simran', name: 'Simran – Cheerful \u2640' },
    { id: 'kavya', name: 'Kavya – Soft \u2640' },
    { id: 'ishita', name: 'Ishita – Confident \u2640' },
    { id: 'shreya', name: 'Shreya – Bright \u2640' },
    { id: 'roopa', name: 'Roopa – Gentle \u2640' },
  ]
};
